[package]
name = "MultiSig"
type = "contract"
authors = [ "" ]
compiler_version = ">=0.18.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v3.0.0-devnet.5", directory = "noir-projects/aztec-nr/aztec" }
wormhole = { git="https://github.com/NethermindEth/wormhole", tag="v3.0.0-flat-no-fees.devnet.5", directory="aztec/contracts" }
